import csv, json, os

ROOT = os.path.dirname(os.path.dirname(__file__))
TC = os.path.join(ROOT, 'test-cases'); PM = os.path.join(ROOT, 'postman')
os.makedirs(TC, exist_ok=True); os.makedirs(PM, exist_ok=True)
H = ['Test ID','Feature','Endpoint','Method','Category','Requirement/SEC','Precondition','Test data','Steps','Expected status','Expected oracle/schema','AI source','Audit label','Audit reason','Corrected version','Postman mapping','Actual result','Bug ID','Evidence']
R=[]
def add(f,n,e,m,c,req,data,status,oracle,src='AI-001',label='VALID',reason='Contract-aligned, executable, oracle defined'):
    if src.startswith('AI') and '/' in status:
        label='INCOMPLETE'; reason='AI supplied multiple possible statuses; human must resolve exact oracle from contract/run'; corrected='Split into separate cases or document one normative expected result'
    else:
        corrected=''
    R.append([f'{f}-{n:03d}',f,e,m,c,req,'Seed data + required actor token',data,'Send request; assert status/body/schema; verify postcondition',status,oracle,src,label,reason,corrected,'Pending Newman mapping','Not executed','', 'Pending authentic evidence'])

# FR04, 40 AI cases
fr04=[
('GET','auth','FR-04, SEC-02','valid user JWT','200','Own profile; no sensitive fields'),('GET','auth','FR-04, SEC-02','no Authorization','401','No disclosure'),('GET','auth','FR-04, SEC-02','malformed Bearer','403','No disclosure'),('GET','schema','FR-04, SEC-01','valid JWT','200','Object schema; password/reset_token absent'),('GET','identity','FR-04','user A JWT','200','Identity bound to token'),('GET','repeat','FR-04','two GET calls','200','Stable schema'),('GET','auth','SEC-02','expired JWT','403','No disclosure'),('GET','security','SEC-04','stored XSS name','200','JSON safe for UI'),('GET','privacy','SEC-01','profile read','200','No plaintext credential'),('GET','idor','FR-04','query id=other','200','/me ignores client ID'),
('PUT','positive','FR-04','all valid fields','200','Fields persist'),('PUT','positive','FR-04','name only','200','Only name changes'),('PUT','positive','FR-04','phone only','200','Only phone changes'),('PUT','positive','FR-04','address only','200','Only address changes'),('PUT','boundary','FR-04','phone 10 digits, 0-prefix','200','Accepted'),('PUT','boundary','FR-04','phone 11 digits, 0-prefix','200','Accepted'),('PUT','boundary','FR-04','phone 9 digits','400','Rejected; unchanged'),('PUT','boundary','FR-04','phone 12 digits','400','Rejected; unchanged'),('PUT','boundary','FR-04','phone no 0-prefix','400','Rejected; unchanged'),('PUT','boundary','FR-04','phone letters','400','Rejected; unchanged'),('PUT','boundary','FR-04','phone hyphens','400','Rejected; unchanged'),('PUT','boundary','FR-04','phone surrounding spaces','400','Reject or documented normalize'),('PUT','boundary','FR-04','phone null','400','Rejected'),('PUT','type','FR-04','phone number type','400','Rejected'),('PUT','boundary','FR-04','name empty','400','Rejected'),('PUT','boundary','FR-04','name whitespace','400','Rejected'),('PUT','boundary','FR-04','Vietnamese Unicode name','200','Safe persistence'),('PUT','boundary','FR-04','name 256 chars','400','Rejected if max applies'),('PUT','security','SEC-04','name script tag','200/400','Escaped/no execution'),('PUT','boundary','FR-04','empty address','400','Validation/documented policy'),('PUT','type','FR-04','empty JSON object','400','No silent overwrite'),('PUT','type','FR-04','JSON null body','400','Validation error'),('PUT','auth','SEC-02','valid body no token','401','No update'),('PUT','auth','SEC-02','malformed token','403','No update'),('PUT','security','SEC-06','role=admin','400/403','Role unchanged'),('PUT','security','SEC-06','role=admin + valid fields','200/400','Role unchanged'),('PUT','security','FR-04','email attacker address','200/400','Email unchanged'),('PUT','security','FR-04','id other user','200/400','Target remains owner'),('PUT','security','FR-04','user_id other user','200/400','Target remains owner'),('PUT','schema','FR-04','valid update','200','Response message schema')]
for i,(m,c,q,d,s,o) in enumerate(fr04,1): add('FR04',i,'/api/users/me',m,c,q,d,s,o)
for i,(d,o) in enumerate([('role escalation + fresh login','Role cannot be escalated'),('Concurrent PUT from two users','No cross-user mixing'),('Control chars/RTL address','No response corruption'),('Replay identical PUT 3 times','Idempotent result'),('Token A plus B identifiers','B profile unchanged')],41): add('FR04',i,'/api/users/me','PUT','human-security','FR-04, SEC-04/06',d,'200/400/403',o,'HUMAN-001')

# FR10: complete 5x5 state matrix = 25 AI
states=['pending','confirmed','shipping','delivered','canceled']; valid={('pending','confirmed'),('pending','canceled'),('confirmed','shipping'),('confirmed','canceled'),('shipping','delivered')}; n=1
for a in states:
    for b in states:
        add('FR10',n,'/api/admin/orders/:id/status','PUT','state-matrix','FR-10',f'current={a}, target={b}','200' if (a,b) in valid else '400',f'Only legal transition; final state={b} iff valid'); n+=1
for d,s,o in [('owner cancels pending','200','Canceled'),('owner cancels confirmed','200','Canceled'),('owner cancels shipping','400','Remains shipping'),('owner cancels delivered','400','Terminal unchanged'),('owner cancels canceled','400','Terminal unchanged'),('user A cancels user B order','404/403','B order unchanged'),('admin cancels pending','200','Canceled')]: add('FR10',n,'/api/orders/:id/cancel','PUT','cancel/ownership','FR-10',d,s,o); n+=1
for d,s,o in [('no token','401','No mutation'),('malformed JWT','403','No mutation'),('regular user admin update','403','Role enforced'),('valid admin transition','200','Transition applied'),('forged role token','403','Signature required'),('missing order','404','Not found'),('id=-1','404','No mutation'),('status missing','400','Validation error'),('status null','400','Validation error'),('uppercase status','400','Strict enum'),('script status','400','No script'),('replay transition','400','No duplicate transition'),('backward transition','400','State unchanged')]: add('FR10',n,'/api/admin/orders/:id/status','PUT','auth-negative','FR-10, FR-12, SEC-02/03',d,s,o); n+=1
for d,o in [('two users same order ID','IDOR blocked'),('rapid competing transitions','Serialized legal state'),('all destinations from canceled','All rejected'),('spoofed admin header','Header grants no role'),('exact status response schema','Only documented fields')]: add('FR10',n,'/api/orders/:id/cancel','PUT','human-state-security','FR-10, SEC-02/03',d,'400/403/404',o,'HUMAN-001'); n+=1

# FR19: 40 AI rows
fr19=[('GET','list','FR-19','admin token','200','All users'),('GET','auth','SEC-02','no token','401','No disclosure'),('GET','auth','SEC-02','malformed token','403','No disclosure'),('GET','auth','SEC-03','regular user token','403','Admin only'),('GET','auth','SEC-03','forged role token','403','Signature required'),('GET','schema','FR-19','admin list','200','Array schema'),('GET','privacy','FR-19','admin list','200','password absent'),('GET','privacy','SEC-01','admin list','200','reset_token absent'),('GET','schema','FR-19','admin list','200','Unique IDs'),('GET','schema','FR-19','admin list','200','JSON Content-Type'),('GET','idor','FR-19','query id other','200','No IDOR'),('GET','repeat','FR-19','two list calls','200','Consistent records'),('DELETE','positive','FR-19','admin deletes disposable','200','Target absent'),('DELETE','positive','FR-19','admin deletes second','200','Only target removed'),('DELETE','negative','FR-19','missing ID','404','No unrelated deletion'),('DELETE','negative','FR-19','id=0','404','No deletion'),('DELETE','negative','FR-19','id=-1','404','No deletion'),('DELETE','negative','FR-19','id=abc','404','No deletion'),('DELETE','negative','FR-19','id=1.5','400/404','No deletion'),('DELETE','negative','FR-19','id=null','400/404','No deletion'),('DELETE','repeat','FR-19','same ID twice','404','Second not success'),('DELETE','auth','SEC-02','no token','401','No deletion'),('DELETE','auth','SEC-02','malformed token','403','No deletion'),('DELETE','auth','SEC-03','regular user','403','Admin only'),('DELETE','auth','SEC-03','forged role token','403','Signature required'),('DELETE','idor','FR-19','user A targets B','403','No deletion'),('DELETE','self-delete','FR-19','admin targets own ID','400/403','Admin remains'),('DELETE','schema','FR-19','valid delete','200','Message schema'),('DELETE','schema','FR-19','missing resource','404','Error schema'),('DELETE','privacy','FR-19','list after delete','200','Deleted absent'),('DELETE','integrity','FR-19','target has orders','409/200','Document referential policy'),('DELETE','type','FR-19','array/object ID','400/404','No deletion'),('DELETE','security','SEC-05','SQL injection ID','400/404','No mass delete'),('DELETE','security','SEC-05','quoted injection ID','400/404','Parameterized'),('GET','privacy','SEC-01','locked user list','200','No credentials'),('GET','authorization','SEC-03','signed admin role','200','Role checked'),('DELETE','authorization','SEC-03','signed user role','403','Role rejected'),('DELETE','concurrency','FR-19','two admins same target','200/404','At most one delete'),('GET','schema','FR-19','empty DB','200','Empty array'),('DELETE','negative','FR-19','whitespace ID','400/404','No deletion')]
for i,(m,c,q,d,s,o) in enumerate(fr19,1): add('FR19',i,'/api/admin/users' if m=='GET' else '/api/admin/users/:id',m,c,q,d,s,o)
for i,(d,o) in enumerate([('admin self-delete fresh token','Self-delete prohibited'),('user deletes admin then admin login','Admin remains'),('SQL injection mass-delete attempt','No mass deletion'),('delete user with active order','Referential policy observed'),('stale JWT after deletion','Authorization behavior documented')],41): add('FR19',i,'/api/admin/users/:id','DELETE','human-security','FR-19, SEC-02/03/05',d,'400/403/404',o,'HUMAN-001')

with open(os.path.join(TC,'member-4.csv'),'w',newline='',encoding='utf-8') as f: csv.writer(f).writerows([H]+R)
with open(os.path.join(TC,'member-4.json'),'w',encoding='utf-8') as f: json.dump([dict(zip(H,x)) for x in R],f,ensure_ascii=False,indent=2)

pre=["pm.request.headers.upsert({key:'X-Student-Id',value:pm.environment.get('studentId')||'23127326'});","pm.request.headers.upsert({key:'Content-Type',value:'application/json'});"]
def t(code,label): return [f"pm.test('{label}',()=>pm.expect(pm.response.code).to.be.oneOf([{','.join(str(x) for x in code)}]));"]
def req(name,m,path,actor,body,exp,label):
    h=[] if m=='POST' and 'login' in name.lower() else [{'key':'Authorization','value':'Bearer {{'+actor+'Token}}'}]
    if body is not None: h.append({'key':'Content-Type','value':'application/json'})
    tests=t(exp,label)
    if 'login admin' in name.lower(): tests += ["pm.environment.set('adminToken',pm.response.json().token);", "pm.environment.set('adminId',String(pm.response.json().user.id));"]
    if 'login user' in name.lower(): tests += ["pm.environment.set('userToken',pm.response.json().token);", "pm.environment.set('userId',String(pm.response.json().user.id));"]
    if 'checkout' in name.lower(): tests += ["pm.environment.set('orderId',String(pm.response.json().orderId));"]
    x={'name':name,'request':{'method':m,'header':h,'url':{'raw':'{{baseUrl}}'+path,'host':['{{baseUrl}}'],'path':path.strip('/').split('/')}},'event':[{'listen':'test','script':{'type':'text/javascript','exec':tests}}]}
    if body is not None: x['request']['body']={'mode':'raw','raw':json.dumps(body)}
    return x
coll={'info':{'name':'HW06 Member 4 — FR04 FR10 FR19','schema':'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'},'event':[{'listen':'prerequest','script':{'type':'text/javascript','exec':pre}}],'variable':[{'key':'baseUrl','value':'http://localhost:3000'},{'key':'studentId','value':'23127326'}],'item':[]}
coll['item']=[req('SETUP login admin','POST','/api/login','user',{'email':'admin@eshop.com','password':'Admin123!'},[200],'admin login'),req('SETUP login user','POST','/api/login','user',{'email':'test@eshop.com','password':'Test1234!'},[200],'user login'),req('FR04 GET profile','GET','/api/users/me','user',None,[200],'profile'),req('FR04 role escalation must reject','PUT','/api/users/me','user',{'name':'Member Four','shipping_address':'Test','phone':'0912345678','role':'admin'},[400,403],'role protected'),req('FR10 checkout pending','POST','/api/checkout','user',{'total_amount':1000,'shipping_address':'Test'},[200],'checkout'),req('FR10 admin transition','PUT','/api/admin/orders/{{orderId}}/status','admin',{'status':'confirmed'},[200],'transition'),req('FR10 illegal delivered→pending','PUT','/api/admin/orders/{{orderId}}/status','admin',{'status':'pending'},[400],'terminal protected'),req('FR19 admin list','GET','/api/admin/users','admin',None,[200],'admin list'),req('FR19 user list must reject','GET','/api/admin/users','user',None,[403],'role enforcement'),req('FR19 self-delete must reject','DELETE','/api/admin/users/{{adminId}}','admin',None,[400,403],'self delete')]
for row in R:
    tid,feature,endpoint,method,category,requirement,_,data,_,expected,oracle,source,label,*_=row
    path=endpoint.replace(':id','{{orderId}}' if feature=='FR10' else '{{userId}}')
    actor='admin' if '/admin/' in path else 'user'
    nums=[int(x) for x in expected.split('/') if x.isdigit()]
    if not nums: nums=[200]
    body=None
    if method=='PUT':
        body={'name':'Member Four','shipping_address':'Test','phone':'0912345678'} if feature=='FR04' else ({'status':'confirmed'} if feature=='FR10' else None)
        if feature=='FR04' and ('role' in data.lower() or 'escalat' in data.lower()): body['role']='admin'
    coll['item'].append({'name':tid+' — '+category,'description':f'{requirement}; {oracle}; audit={label}','request':req(tid,method,path,actor,body,nums,'case '+tid)['request'],'event':req(tid,method,path,actor,body,nums,'case '+tid)['event']})
with open(os.path.join(PM,'HW06_member4_collection.json'),'w',encoding='utf-8') as f: json.dump(coll,f,ensure_ascii=False,indent=2)
env={'id':'hw06-member4-local','name':'HW06 Member 4 Local','values':[{'key':'baseUrl','value':'http://localhost:3000','enabled':True},{'key':'studentId','value':'23127326','enabled':True},{'key':'adminToken','value':'','enabled':True},{'key':'userToken','value':'','enabled':True},{'key':'adminId','value':'1','enabled':True},{'key':'userId','value':'2','enabled':True},{'key':'orderId','value':'','enabled':True}], '_postman_variable_scope':'environment'}
with open(os.path.join(PM,'HW06_member4_environment.json'),'w',encoding='utf-8') as f: json.dump(env,f,ensure_ascii=False,indent=2)
print('rows',len(R),'collection items',len(coll['item']))
